export enum Url {
    ServerBaseUrl = "http://localhost:8081",
    AngularBaseUrl = "http://localhost:4200",
    AssetsTechInfoPath = "/assets/technology/",
    AssetsBlogPath = "/blog/",
    AddBlog = "/addBlog",
    AddTechnologyInfo = "/addTechInfo",
    BlogSave = "/blog/save",
    GetBlog = "/blog/details/",
    AllBlogs = "/blog/all",
    Upload = "/blog/upload",
    SaveTechInfo = "/blog/saveTechInfo",
    GetSingleTechInfo = "/blog/techInfo/",
    AllTechInfo = "/blog/allTechInfo",
    GetImage = "/blog/getImage/",
    Technologies = "/dropDown/technologies",
    SubTechnologies = "/dropDown/subTechnologies/",
    SequenceId = "/blog/sequenceId",
    AllTechnologyWithSubTechs = "/blog/getTechAndSubTechs"
}
